### ISSUE TITLE
Use of "unistd.h" and "sys/*.h" in src/MessageQueue is not portable for Windows

### ISSUE THREAD

**Issue by Grigler** [NCCA/NGL#17]

**Comment by jmacey** [comment]
Yes still work in progress for Windows. For now just comment out code that doesn’t work and the cout code should work fine.

Jon

On 19 Oct 2018, at 13:39, Graham Rigler <notifications@github.com<mailto:notifications@github.com>> wrote:


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCCA%2FNGL%2Fissues%2F17&data=02%7C01%7C%7Cd2e699931e284e5e1ce108d635bfd8ea%7Cede29655d09742e4bbb5f38d427fbfb8%7C0%7C0%7C636755495424452350&sdata=pVCi72mwvgXVQ01SwaALGDNA%2Bo2vA3f0HGc%2FDI5c4N4%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAASuG1ZGiyqnWphOH1UikyimMa1AD_T4ks5umcfigaJpZM4XwRvt&data=02%7C01%7C%7Cd2e699931e284e5e1ce108d635bfd8ea%7Cede29655d09742e4bbb5f38d427fbfb8%7C0%7C0%7C636755495424462355&sdata=l%2F3QU2DoyuqLfXWRyI%2FTljt7%2Fac5uEhWz35kvZLG9JQ%3D&reserved=0>.

BU is a Disability Confident Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages. This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.

**Comment by robthebloke** [comment]
io.h with some #defines to munge "_open" to "open"?
https://msdn.microsoft.com/en-us/library/40bbyw78.aspx
